<a href="https://colab.research.google.com/github/roman-mikhaylov/repo_sinergiya/blob/main/dz_6_lesson.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

*Курсив*

**Задание №6: Numpy Stats. Основные статистики**

Задачи:
1 Перечислите (можно не на память, просто их нужно держать перед глазами и уметь ими
пользоваться) статистические характеристики. Повторите за спикером примеры их
использования.

In [ ]:
import numpy as np
arr = np.array([1,2,3,4,5,6,7,8,2,45,-2,0])
arr = arr.reshape(3,4)
arr

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 2, 45, -2,  0]])

Основные статистические характеристики
amin(a[, axis, out, keepdims, initial])

**общее описание параметров функций по уроку**
 на примере nanpercentile(a, q, axis=None, out=None, overwrite_input=False, method='linear', keepdims=np._NoValue, *, interpolation=None)

Возвращает q-й процентиль элементов массива.

**Параметры**
**a : array_like**
    Входной массив или объект, который можно преобразовать в массив, содержащий значения nan, которые следует игнорировать.
**q : array_like of float**
    Процентиль или последовательность процентилей для вычисления, которая должна находиться в диапазоне от 0 до 100 включительно.
**ось:** {int, кортеж из целых чисел, None}, необязательная
    ось или оси, по которым вычисляются процентили. По умолчанию процентиль вычисляется по сплющенной версии массива.
**out : ndarray, необязательный**
    Альтернативный выходной массив, в который можно поместить результат. Он должен иметь ту же форму и длину буфера, что и ожидаемый результат, но при необходимости тип (вывода) будет преобразован.
**overwrite_input : bool, необязательно.**
     Если True, то разрешить изменение
    входного массива посредством промежуточных вычислений для экономии памяти. aВ этом случае содержимое ввода aпосле завершения этой функции не определено.
**метод: str, необязательный.**
    Этот параметр указывает метод, используемый для оценки процентиля.

Минимальное значение элементов массива. Параметр axis позволяет указывать оси,
вдоль которых необходим поиск минимальных значений.
amax(a[, axis, out, keepdims, initial])

In [ ]:
# минимум по матрице по строкам
np.amin(arr, axis = 0)

array([ 1,  2, -2,  0])

In [ ]:
# минимум по матрице по столбцам
np.amin(arr, axis = 1)

array([ 1,  5, -2])

Максимальное значение в массиве. Параметр axis позволяет указывать оси, вдоль
которых необходим поиск максимальных значений.
nanmin(a[, axis, out, keepdims])


In [ ]:
# малсимум по матрице по строкам
np.amax(arr, axis = 0)

array([ 5, 45,  7,  8])

In [ ]:
# минимум по матрице по столбцам
np.amax(arr, axis = 1)

array([ 4,  8, 45])

Минимальное значение массива или минимальное значение вдоль указанной оси.
Элементы с значением np.nan игнорируются.
nanmax(a[, axis, out, keepdims])


Максимальное значение массива или максимальное значение вдоль указанной оси.
Элементы с значением np.nan игнорируются.numpy.ptp(a[, axis, out, keepdims])


In [ ]:
nan_arr = np.array([1,3,4,np.nan, 5, -23])
nan_arr = nan_arr.reshape(3,2)
print(nan_arr)
print(f'{np.nanmin(nan_arr, axis = 0)}  минимум по строкам')
print(f'{np.nanmin(nan_arr, axis = 1)}  минимум по столбцам')
print(f'{np.nanmax(nan_arr, axis = 0)}  максимум по строкам')
print(f'{np.nanmax(nan_arr, axis = 1)}  максимум по столбцам')
print(f'{np.nanmin(nan_arr)}  минимум по массиву')
print(f'{np.nanmax(nan_arr)}  максимум по массиву')

[[  1.   3.]
 [  4.  nan]
 [  5. -23.]]
[  1. -23.]  минимум по строкам
[  1.   4. -23.]  минимум по столбцам
[5. 3.]  максимум по строкам
[3. 4. 5.]  максимум по столбцам
-23.0  минимум по массиву
5.0  максимум по массиву


Возвращает диапазон значений ([max - min]) массива или указанной оси массива.
numpy.percentile(a, q[, axis, out, overwrite_input, interpolation, keepdims])

In [ ]:
arr

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 2, 45, -2,  0]])

In [ ]:
np.ptp(arr) # 45-(-2)  по всему массиву

47

In [ ]:
np.ptp(arr, axis = 0) #   по столбцам

array([ 4, 43,  9,  8])

In [ ]:
np.ptp(arr, axis = 1) #   по строкам

array([ 3,  3, 47])

Вычисляет q-й процентиль (перцентиль) значений элементов массива или элементов
вдоль указанной оси numpy.nanpercentile(a, q[, axis, out, overwrite_input, interpolation, keepdims])

Вычисление q-го процентиля (перцентиля) значений вдоль указанной оси массива.
]Элементы с значением np.nan игнорируются.
numpy.quantile(a, q[, axis, out, overwrite_input, interpolation, keepdims])

In [ ]:
perc = 60
array = np.random.randn(100_000) # распределение Гаусса для 100 000 случайных значений в центром в "0" и дисперсией = 1
array = np.sort(array)
ind = int(array.shape[0]*perc/100)
array[ind]

0.26240352038053605

In [ ]:
# с пмощью np
np.percentile(array, 60)

0.26239841159786687

In [ ]:
# добавим nan  в массив
array[0] = np.nan
np.nanpercentile(array, 60)

0.26240181745297964

Вычисление q-го процентиля (перцентиля) значений вдоль указанной оси массива.
Элементы с значением np.nan игнорируются.

In [ ]:
np.nanpercentile(array, 60, axis = 0)


0.26240181745297964

Дисперсия значений элементов массива расположенных вдоль указанной оси.
nanmedian(a[, axis, out, overwrite_input, …])

Медиана значений элементов массива расположенных вдоль указанной оси. Элементы с
значением NaN игнорируются.
nanmean(a[, axis, dtype, out, keepdims])

Средние и отклонения
median(a[, axis, out, overwrite_input, keepdims])


In [ ]:
np.median(array)

nan

In [ ]:
np.nanmedian(array)

0.004522366788869584

Медиана значений элементов массива, расположенных вдоль указанной оси.
average(a[, axis, weights, returned])

In [ ]:
array1 = np.random.randn(100_000) # распределение Гаусса для 100 000 случайных значений в центром в "0" и дисперсией = 1
array1 = np.sort(array1)

In [ ]:
np.average(array1, axis = 0)

-0.001611959332735587

In [ ]:
arr = np.arange(1,10)
weight = 1/arr
np.average(arr, weights=weight)

3.181371861411138

Средневзвешенное значений элементов массива расположенных вдоль указанной оси.
mean(a[, axis, dtype, out, keepdims])

In [ ]:
np.mean(array1)

-0.001611959332735587

Среднее арифметическое значений элементов массива расположенных вдоль указанной
оси.
std(a[, axis, dtype, out, ddof, keepdims])

Стандартное отклонение значений элементов массива расположенных вдоль указанной
оси.
var(a[, axis, dtype, out, ddof, keepdims])

In [ ]:
np.std(array1) # стандартное отклонение

1.0010658833915964

In [ ]:
np.var(array1) # дисперсия

1.0021329028905974

Среднее арифметическое значений элементов массива расположенных вдоль указанной
оси. Элементы с значением NaN игнорируются.
nanstd(a[, axis, dtype, out, ddof, keepdims])

In [ ]:
np.nanstd(array)

1.002551132487219

Стандартное отклонение значений элементов массива расположенных вдоль указанной
оси. Элементы с значением NaN игнорируются.
nanvar(a[, axis, dtype, out, ddof, keepdims])


Дисперсия значений элементов массива расположенных вдоль указанной оси. Элементы
с значением NaN игнорируются.

In [ ]:
np.nanvar(array)

1.0051087732514052

Корреляции
corrcoef(x[, y, rowvar, bias, ddof])

Корреляция объясняет, насколько изменение одной переменной приводит к изменению пропорции второй переменной. Корреляция варьируется от -1 до +1. Если значение корреляции равно 0, это означает, что между переменными нет линейной зависимости, однако могут существовать другие функциональные связи.

In [ ]:
a = np.arange(10)
b = a[::-1]
np.corrcoef(a,b)

array([[ 1., -1.],
       [-1.,  1.]])

In [ ]:
'''
создадим некторый шум дл b
'''
noisy_b = b + np.random.randn(b.shape[0]) * b.std()/10
noisy_b

array([ 8.88926066,  8.10481568,  7.40362157,  6.06826448,  4.83394338,
        3.90748695,  2.93503073,  2.41778272,  0.66676644, -0.10951585])

In [ ]:
np.corrcoef(a, b + noisy_b)

array([[ 1.        , -0.99926688],
       [-0.99926688,  1.        ]])

Коэфициент корреляции Пирсона.
correlate(a, v[, mode])

In [120]:
# показывает коррелляцию двух одно мерных последовательностей
a = np.random.randn(100)
b = a.reshape(-1)
np.correlate(a, b)


array([84.64999512])

Взаимнокорреляционная функция двух одномерных последовательностей.
cov(m[, y, rowvar, bias, ddof, fweights, …])

Ковариационная матрица.


Ковариация указывает на уровень, до которого две переменные изменяются вместе
Положительное значение показывает, что обе переменные изменяются в одном направлении, а отрицательное значение показывает, что они изменяются в противоположном направлении.

In [128]:
x = [-2.1, -1,  4.3]
y = [3,  1.1,  0.12]
X = np.stack((x, y), axis=0)
np.cov(x)
np.cov(x,y)
np.cov(X)

array([[11.71      , -4.286     ],
       [-4.286     ,  2.14413333]])

Гистограммы
histogram(a[, bins, range, normed, weights, …])

In [130]:
# вычисляет гистограмму набора данных
np.histogram([1, 2, 1], bins=[0, 1, 2, 3])


(array([0, 2, 1]), array([0, 1, 2, 3]))

Вычисление гистограммы набора данных.
histogram2d(x, y[, bins, range, normed, weights])

In [132]:
# выисляет гистограмму двух наоров данных
xedges = [0, 1, 3, 5]
yedges = [0, 2, 3, 4, 6]
x = np.random.normal(2, 1, 100)
y = np.random.normal(1, 1, 100)
H, xedges, yedges = np.histogram2d(x, y, bins=(xedges, yedges))
H

array([[12.,  1.,  1.,  0.],
       [43., 11.,  1.,  0.],
       [13.,  3.,  0.,  0.]])

Вычисление двумерной гистограммы двух наборов данных.
histogramdd(sample[, bins, range, normed, …])

In [136]:
 # вычисляет гистограмму нескольких наборов данных
r = np.random.randn(100,3)
H, edges = np.histogramdd(r, bins = (5, 8, 4))
H.shape, edges[0].size, edges[1].size, edges[2].size


((5, 8, 4), 6, 9, 5)

Вычисление N-мерной гистограммы N-го количества наборов данных.
bincount(x[, weights, minlength])
Количество вхождений значений в массиве.
numpy.histogram_bin_edges(a, bins=10, range=None, weights=None)

In [139]:
np.arange(5)
np.bincount(np.arange(5)) # кол-во вхождение

array([1, 1, 1, 1, 1])

In [143]:
 # Функция для расчета только границ интервалов, используемых функцией histogram .
arr = np.array([0, 0, 0, 1, 2, 3, 3, 4, 5])
np.histogram(arr)
np.histogram_bin_edges(arr, bins='auto', range=(0, 1))


array([0.  , 0.25, 0.5 , 0.75, 1.  ])

Значения для прямоугольников гистограммы.
digitize(x, bins[, right])

In [144]:
x = np.array([0.2, 6.4, 3.0, 1.6])
bins = np.array([0.0, 1.0, 2.5, 4.0, 10.0])
inds = np.digitize(x, bins)
inds

array([1, 4, 3, 2])

Вычисление индексов числовых интервалов массива bins в которые входит каждое
последующее значение элемента массива x.