<a href="https://colab.research.google.com/github/roman-mikhaylov/repo_sinergiya/blob/main/less_3_PA.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
from numpy import random

In [ ]:
# сгенерим слцчайное целое число от 0 до N

N = 100
random.randint(N)

61

In [11]:
# случайное вещественное от 0 до 1
random.rand()

0.15012133842994313

In [12]:
# случайное от 0 до 100
random.rand()*100

82.37136735960681

In [14]:
# генерация массива из случайных целых
x = random.randint(100, size = 3)
x

array([32,  9, 10])

In [16]:
# генерация массива из случайных целых двуменрный
x = random.randint(100, size = (3,5))
x

array([[20, 28, 99, 79, 56],
       [14, 37, 59, 33, 40],
       [ 0, 95, 96,  3,  7]])

In [19]:
y = random.rand(3,5)*100 # здесь 3 5 размер
y

array([[74.91333727, 31.37687304, 98.81222467, 82.09810253, 69.67727117],
       [33.3396177 , 78.31831477, 21.10584682, 41.48415428, 67.25439754],
       [91.42910964, 96.9837018 , 60.15033508, 78.26479991, 90.61652286]])

In [24]:
# случайный выбор
z = random.choice([2, 'tr', 3, 6, 7])
z

'tr'

In [28]:
# новый массив из набора элементов
s = random.choice([1,3,4,6,2,8], size = (3,5))
s

array([[2, 1, 8, 3, 2],
       [2, 1, 3, 4, 4],
       [6, 1, 1, 8, 2]])

In [31]:
# решение задачи про Машу и 18 платьев
colors=['желтый', 'зеленый', 'синий', 'красный', 'оранжевый']
x = random.choice(colors, size=(18), p=[1/3, 1/6, 0, 1/2, 0]) # p - вероятности по цвету сумма p == 1
x

array(['желтый', 'желтый', 'желтый', 'красный', 'красный', 'зеленый',
       'красный', 'желтый', 'красный', 'красный', 'красный', 'красный',
       'зеленый', 'красный', 'красный', 'зеленый', 'красный', 'красный'],
      dtype='<U9')

In [32]:
# подсчет элементов внутри массива
(x== 'желтый').astype(int).sum()

4