<a href="https://colab.research.google.com/github/roman-mikhaylov/repo_sinergiya/blob/main/numpy_less_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [7]:
A = np.array([[1,2,3],[4,5,6],[7,8,9]])
A

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [4]:
A[0]

array([1, 2, 3])

In [5]:
A[0][0]

1

In [6]:
A [:,1]

array([2, 5, 8])

изменеие массива

In [8]:
# форма массива: 3-строки 3 столбца
A.shape

(3, 3)

In [36]:
# изменние формы массива
A = np.array([[1,2,3,4,5,6],[7,8,9,10,11,12]])
A

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12]])

In [11]:
A.shape

(2, 6)

In [21]:
A_reshape = A.reshape(6,2)
A_reshape


array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10],
       [11, 12]])

In [22]:
A_reshape.shape

(6, 2)

In [19]:
# вытянуть в один список
A1_reshape = A.reshape(1,12)
# в один столбец
A2_reshape = A.reshape(12,1)
A1_reshape

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12]])

In [ ]:
A2_reshape

In [23]:
# 6*2 = 12 элементов. если нужно сделать массии со стороной 2, другая - 3, а третья ... 12/(3*2) = 2
A3_reshape = A.reshape(2,3,2)
A3_reshape

array([[[ 1,  2],
        [ 3,  4],
        [ 5,  6]],

       [[ 7,  8],
        [ 9, 10],
        [11, 12]]])

In [24]:
A3_reshape.shape

(2, 3, 2)

In [26]:
A3_reshape = A.reshape(2,3,-1) # если не хотим считать размерность
A3_reshape

array([[[ 1,  2],
        [ 3,  4],
        [ 5,  6]],

       [[ 7,  8],
        [ 9, 10],
        [11, 12]]])

транспонирование - измение порядка следования осей

In [33]:
B = np.zeros((1,2,3,4,5,6))
B.shape

(1, 2, 3, 4, 5, 6)

In [34]:
B_trans = B.T
B_trans.shape

(6, 5, 4, 3, 2, 1)

In [37]:
# отличие транспонирования и reshape
A

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12]])

In [39]:
A_transp = A.T
A_transp

array([[ 1,  7],
       [ 2,  8],
       [ 3,  9],
       [ 4, 10],
       [ 5, 11],
       [ 6, 12]])

In [40]:
A_reshape = A.reshape(6,2)
A_reshape

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10],
       [11, 12]])

In [52]:
A1_transposed = np.transpose(A, (1,0))
A1_transposed.shape

(6, 2)

In [53]:
A1_transposed

array([[ 1,  7],
       [ 2,  8],
       [ 3,  9],
       [ 4, 10],
       [ 5, 11],
       [ 6, 12]])

создание массивов

In [58]:
# контатенация - обьединние массивов в один с сохранением кол-ва осей
A = np.zeros((5,6))
B = np.ones_like(A)

In [56]:
A

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [59]:
B

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [60]:
np.concatenate((A,B), axis = 0) # axis=0 сложение по оси строк

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [61]:
np.concatenate((A,B), axis = 1) # конкатинация по оси столбцов

array([[0., 0., 0., 0., 0., 0., 1., 1., 1., 1., 1., 1.],
       [0., 0., 0., 0., 0., 0., 1., 1., 1., 1., 1., 1.],
       [0., 0., 0., 0., 0., 0., 1., 1., 1., 1., 1., 1.],
       [0., 0., 0., 0., 0., 0., 1., 1., 1., 1., 1., 1.],
       [0., 0., 0., 0., 0., 0., 1., 1., 1., 1., 1., 1.]])

In [62]:
np.concatenate((A,B), axis = -1) # конкатинация по последней оси

array([[0., 0., 0., 0., 0., 0., 1., 1., 1., 1., 1., 1.],
       [0., 0., 0., 0., 0., 0., 1., 1., 1., 1., 1., 1.],
       [0., 0., 0., 0., 0., 0., 1., 1., 1., 1., 1., 1.],
       [0., 0., 0., 0., 0., 0., 1., 1., 1., 1., 1., 1.],
       [0., 0., 0., 0., 0., 0., 1., 1., 1., 1., 1., 1.]])

In [67]:
A = np.zeros((5,6))
B = np.ones((5,6))
np.concatenate((A,B), axis = 0)

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [68]:
# если нужно соединить по новой оси (типа 3д)
np.stack((A,B), axis = 0).shape

(2, 5, 6)

In [71]:
np.stack((A,B), axis = 0)

array([[[0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.]],

       [[1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.]]])

In [72]:
np.stack((A,B), axis = 1).shape

(5, 2, 6)

In [74]:
np.stack((A,B), axis = 1)

array([[[0., 0., 0., 0., 0., 0.],
        [1., 1., 1., 1., 1., 1.]],

       [[0., 0., 0., 0., 0., 0.],
        [1., 1., 1., 1., 1., 1.]],

       [[0., 0., 0., 0., 0., 0.],
        [1., 1., 1., 1., 1., 1.]],

       [[0., 0., 0., 0., 0., 0.],
        [1., 1., 1., 1., 1., 1.]],

       [[0., 0., 0., 0., 0., 0.],
        [1., 1., 1., 1., 1., 1.]]])

In [75]:
np.stack((A,B), axis = -1)

array([[[0., 1.],
        [0., 1.],
        [0., 1.],
        [0., 1.],
        [0., 1.],
        [0., 1.]],

       [[0., 1.],
        [0., 1.],
        [0., 1.],
        [0., 1.],
        [0., 1.],
        [0., 1.]],

       [[0., 1.],
        [0., 1.],
        [0., 1.],
        [0., 1.],
        [0., 1.],
        [0., 1.]],

       [[0., 1.],
        [0., 1.],
        [0., 1.],
        [0., 1.],
        [0., 1.],
        [0., 1.]],

       [[0., 1.],
        [0., 1.],
        [0., 1.],
        [0., 1.],
        [0., 1.],
        [0., 1.]]])

In [76]:
np.stack((A,B), axis = -1).shape

(5, 6, 2)

срезы

In [85]:
# создание массива с reshape
A = np.arange(0,60).reshape(6,10)
A

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59]])

In [88]:
A[2:5, 2:7] # срезы

array([[22, 23, 24, 25, 26],
       [32, 33, 34, 35, 36],
       [42, 43, 44, 45, 46]])

In [90]:
''''
фильтрация массива при помощью индексируббщего массива
'''
arr = np.array([3,4,5,67])
x = [True, True, False, True]

newarr = arr[x]
newarr

array([ 3,  4, 67])

In [91]:
index_array = [True if x > 4 else False for x in arr]
index_array

[False, False, True, True]

In [92]:
arr[index_array]

array([ 5, 67])

In [93]:
# или так
index_array = arr > 4
index_array

array([False, False,  True,  True])

In [94]:
arr[arr>4]

array([ 5, 67])

In [103]:
# поиск ао условию в массиве
A = np.array([1,2,3,4,4,4,6,4])
x = np.where(A == 4)
x                             # индексирующий массив

(array([3, 4, 5, 7]),)

In [104]:
A[x]

array([4, 4, 4, 4])

In [105]:
# пример получения нечетных чисел
A = np.array([1,2,3,4,4,4,6,4])
x = np.where(A % 2 == 1)
A[x]

array([1, 3])

In [106]:
 '''
 поиск в отсортированном массиве
 '''
 arr = np.array([3,5,7,9])
 x = np.searchsorted(arr, 7)
 x

2

In [107]:
arr_1 = arr[::-1]
arr_1

array([9, 7, 5, 3])

In [108]:
np.sort(arr)

array([3, 5, 7, 9])

In [112]:
# сортировка по выделенной оси
arr = np.arange(20,0, -1 ).reshape(5,4)
arr

array([[20, 19, 18, 17],
       [16, 15, 14, 13],
       [12, 11, 10,  9],
       [ 8,  7,  6,  5],
       [ 4,  3,  2,  1]])

In [113]:
np.sort(arr) # так по строкам получается сортировка

array([[17, 18, 19, 20],
       [13, 14, 15, 16],
       [ 9, 10, 11, 12],
       [ 5,  6,  7,  8],
       [ 1,  2,  3,  4]])

In [116]:
np.sort(arr, axis = 0) # по столбцам

array([[ 4,  3,  2,  1],
       [ 8,  7,  6,  5],
       [12, 11, 10,  9],
       [16, 15, 14, 13],
       [20, 19, 18, 17]])

In [121]:
np.sort(np.sort(arr, axis =0), axis=-1) # сортировка по обоим осям

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20]])

# Новый раздел