**1 Опишите своими словами как выглядит однородный двумерный массив?**

Он выглядит как таблица со столбцами и строками (две Оси == два измерения) и элементами ( ячейки таблицы) внутри

In [4]:
 import numpy as np
 arr = np.arange(0, 16).reshape(4,4)
 arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

**2 Что произойдёт с этим массивом, если добавится третья ось?**

Массив станет трехмерным. Все элементы должны иметь один тип данных. Может быть создан путем контатации двух массивов по любой из осей

In [11]:
arr.shape

(4, 4)

In [12]:
b = np.ones_like(arr)
np.stack((arr,b), axis = 0).shape

(2, 4, 4)

**3 Какие вычисления способна производить NumPy с этими данными?**

Если A и B массивы одинакового размера, то их можно складывать, умножать, вычитать, делить и возводить в степень. Эти операции выполняются поэлементно, результирующий массив будет совпадать по геометрии с исходными массивами, а каждый его элемент будет результатом выполнения соответствующей операции над парой элементов из исходных массивов.

**4 Пусть дан массив e  = np.array([(1,2,3), (4,5,6)]). Реализуйте в NumPy простейший срез по рядам**

In [13]:
e = np.array([(1,2,3),(4,5,6)])
e

array([[1, 2, 3],
       [4, 5, 6]])

In [40]:
x = e[:1] # срез по первому ряду  с шагом 1
x

array([[1, 2, 3],
       [4, 5, 6]])